[package]
name = "vdr_ts_nif"
version = "0.1.0"
edition = "2021"

[lib]
name = "vdr_ts_nif"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.37.2"
im = "15.1.0"
indexset = "0.12.3"
ordered-float = "4.2"
ouroboros = "0.18.5"
mlua = { version = "0.10", features = ["luajit", "vendored", "send"] }
rand = "0.8"

[profile.release]
debug = true
force-frame-pointers = true
